apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: redpanda
  name: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redpanda
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: redpanda
    spec:
      containers:
        - args:
            - redpanda
            - start
            - --overprovisioned
            - --smp
            - "1"
            - --memory
            - 10G
            - --reserve-memory
            - 5M
            - --node-id
            - "0"
            - --check=false
          image: vectorized/redpanda:latest
          name: redpanda-c
          ports:
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
status: {}
